include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - library_names
    - avoid_empty_else
    - unnecessary_brace_in_string_interps
    - avoid_redundant_argument_values
    - leading_newlines_in_multiline_strings
    - sort_constructors_first
    - camel_case_extensions
    - constant_identifier_names
    - directives_ordering
    - prefer_single_quotes
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments