name: pokedex
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  injectable: ^1.5.3
  get_it: ^7.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  sqlite3_flutter_libs: ^0.5.8
  drift: ^1.7.1
  path_provider: ^2.0.11
  chucker_flutter: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  mocktail: ^0.3.0
  drift_dev: ^1.7.0

flutter:
  uses-material-design: true