name: pokedex
description: "Pokedex project using Pokeapi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
