name: Code Coverage Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      
      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Install dependencies
        run: flutter pub get
        working-directory: pokedex
    
      - name: Run tests
        run: |
          flutter test --coverage
          lcov --list coverage/lcov.info
          if [ -f coverage/lcov.info ]; then
            find lib -name '*.dart' | xargs -I {} lcov --add-tracefile coverage/lcov.info --output-file coverage/lcov.info
            lcov --remove coverage/lcov.info 'lib/generated/*' --output-file coverage/lcov.info
          fi
        working-directory: pokedex

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
